### ISSUE TITLE
How to pass sasl password to producer and client

### ISSUE THREAD

**Issue by Broever101** [dfdx/RDKafka.jl#17]
I have a Redpanda instance configured on a server with sasl authentication. The password is breaking the communication; the connection is established and producer can write to it but consumer can't read it. The Python Kafka API has an option for `sasl_plain_password` for both producer and consumer. Is that the solution?

**Comment by dfdx** [comment]
If by Python Kafka API you mean confluent-kafka-python package, then RDKafka.jl should behave very similarly since both are based on C library `librdkafka` and thus should accept the same configs. See [this](https://github.com/dfdx/RDKafka.jl#configuration) section and the linked `librdkafka` configuration page.
